global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hahl-lab'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'flask-app-instances'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
          - 'flask-app-1:5000'
          - 'flask-app-2:5000'
          - 'flask-app-3:5000'
          - 'flask-app-4:5000'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
